-- -------- < TF_scripts_2 > --------
--
--                    SCRIPT DE DELECAO (DML)
--
-- Data Criacao ...........: 07/06/2024
-- Autor(es) ..............: PEDRO GARCIA, LUCAS BOTTINO
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_scripts_2
--
-- PROJETO => 01 Base de Dados
--         => 18 Tabelas
--
-- ---------------------------------------------------------

DROP TABLE IF EXISTS ITEM_PEDIDO;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS TIPO_ITEM;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS SERVICO;
DROP TABLE IF EXISTS TIPO_SERVICO;
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS DIARIA;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS TIPO_EVENTO;
DROP TABLE IF EXISTS CATALOGO; 
DROP TABLE IF EXISTS FORNECEDOR; 
DROP TABLE IF EXISTS LUGAR;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS FUNCIONARIO_FIXO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS TIPO_FUNCIONARIO;