-- -------- < TF_scripts_2 > --------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 07/06/2024
-- Autor(es) ..............: PEDRO GARCIA, LUCAS BOTTINO
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_scripts_2
--
--
-- PROJETO => 01 Base de Dados
--         => 18 Tabelas
-- Ultimas Alteracoes
-- 07/06/2024 => Criacao do banco de dados			  
--            => Inclusao de todas as tabelas
-- -----------------------------------

CREATE DATABASE
	IF NOT EXISTS TF_scripts_2;

USE TF_scripts_2;

CREATE TABLE TIPO_FUNCIONARIO(
	idTipoFuncionario INT AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
  salario DECIMAL(6,2) NOT NULL,
    CONSTRAINT TIPO_FUNCIONARIO_PK PRIMARY KEY (idTipoFuncionario)
) ENGINE = InnoDB;

CREATE TABLE FUNCIONARIO (
	idFuncionario INT AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
  cpf DECIMAL(11) NOT NULL,
  dataNascimento DATE,
  classificacao DECIMAL(1) NOT NULL,
  idTipoFuncionario INT NOT NULL,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (idFuncionario),
    CONSTRAINT FUNCIONARIO_TIPO_FUNCIONARIO_FK FOREIGN KEY (idTipoFuncionario)
      REFERENCES TIPO_FUNCIONARIO (idTipoFuncionario)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE FUNCIONARIO_FIXO (
	idFuncionarioFixo INT AUTO_INCREMENT,
  numeroCarteiraTrabalho DECIMAL NOT NULL,
  numeroCertidao DECIMAL NOT NULL,
  grauEscolaridade VARCHAR(2) NOT NULL,
  numeroTituloEleitor DECIMAL NOT NULL,
  idFuncionario INT NOT NULL,
    CONSTRAINT FUNCIONARIO_FIXO_PK PRIMARY KEY (idFuncionarioFixo),
    CONSTRAINT FUNCIONARIO_FIXO_FUNCIONARIO_FK FOREIGN KEY (idFuncionario)
      REFERENCES FUNCIONARIO (idFuncionario)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE ENDERECO (
  idEndereco INT AUTO_INCREMENT,
  logradouro VARCHAR(100) NOT NULL,
  numeroRua VARCHAR(6) NOT NULL,
  nomeCidade VARCHAR(50) NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (idEndereco)
) ENGINE = InnoDB;

CREATE TABLE LUGAR (
	idLugar INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  idEndereco INT NOT NULL,
    CONSTRAINT LUGAR_PK PRIMARY KEY (idLugar),
	  CONSTRAINT LUGAR_ENDERECO_FK FOREIGN KEY (idEndereco) 
      REFERENCES ENDERECO (idEndereco) 
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE TIPO_EVENTO (
  idTipoEvento INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
    CONSTRAINT TIPO_EVENTO_PK PRIMARY KEY (idTipoEvento)
) ENGINE = InnoDB;

CREATE TABLE EVENTO (
	idEvento INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  data DATE NOT NULL,
  horaInicio TIME NOT NULL,
  horaFim TIME NOT NULL,
  idTipoEvento INT NOT NULL,
  idLugar INT NOT NULL,
    CONSTRAINT EVENTO_PK PRIMARY KEY (idEvento),
	  CONSTRAINT EVENTO_TIPO_EVENTO_FK FOREIGN KEY (idTipoEvento)
		  REFERENCES TIPO_EVENTO (idTipoEvento)
		  ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT EVENTO_LUGAR_FK FOREIGN KEY (idLugar)
		  REFERENCES LUGAR (idLugar)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE DIARIA (
	idDiaria INT AUTO_INCREMENT,
  idEvento INT NOT NULL,
  idFuncionario INT NOT NULL,
    CONSTRAINT DIARIA_PK PRIMARY KEY (idDiaria),
	  CONSTRAINT DIARIA_EVENTO_FK FOREIGN KEY (idEvento)
      REFERENCES EVENTO (idEvento)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT DIARIA_FUNCIONARIO_FK FOREIGN KEY (idFuncionario)
		  REFERENCES FUNCIONARIO (idFuncionario)
		  ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE FORNECEDOR (
	idFornecedor INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  idLugar INT NOT NULL,
  idEndereco INT NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (idFornecedor),
    CONSTRAINT FORNECEDOR_LUGAR_FK FOREIGN KEY (idLugar)
      REFERENCES LUGAR (idLugar)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY (idEndereco)
      REFERENCES ENDERECO (idEndereco)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE CLIENTE (
  idCliente INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (idCliente)
) ENGINE = InnoDB;

CREATE TABLE CONTRATO (
	idContrato INT AUTO_INCREMENT,
  quantidadePessoas DECIMAL(5),
  idCliente INT,
  idEvento INT,
    CONSTRAINT CONTRATO_PK PRIMARY KEY (idContrato),
    CONSTRAINT CONTRATO_CLIENTE_FK FOREIGN KEY (idCliente)
      REFERENCES CLIENTE (idCliente)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT CONTRATO_EVENTO_FK FOREIGN KEY (idEvento)
      REFERENCES EVENTO (idEvento)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE TIPO_SERVICO (
    idTipoServico INT AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    preco DECIMAL(6,2) NOT NULL,
      CONSTRAINT TIPO_SERVICO_PK PRIMARY KEY (idTipoServico)
) ENGINE = InnoDB;

CREATE TABLE SERVICO (
	idServico INT AUTO_INCREMENT,
  idTipoServico INT NOT NULL,
    CONSTRAINT SERVICO_PK PRIMARY KEY (idServico),
	  CONSTRAINT SERVICO_TIPO_SERVICO_FK FOREIGN KEY (idTipoServico) 
      REFERENCES TIPO_SERVICO (idTipoServico)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE PEDIDO (
    idPedido INT AUTO_INCREMENT,
    idServico INT NOT NULL,
    idContrato INT NOT NULL,
    CONSTRAINT PEDIDO_PK PRIMARY KEY (idPedido),
	  CONSTRAINT PEDIDO_CONTRATO_FK FOREIGN KEY (idContrato)
      REFERENCES CONTRATO (idContrato)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT PEDIDO_SERVICO_FK FOREIGN KEY (idServico)
      REFERENCES SERVICO (idServico)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE CATALOGO (
	idCatalogo INT AUTO_INCREMENT,
  idLugar INT NOT NULL,
    CONSTRAINT CATALOGO_PK PRIMARY KEY (idCatalogo),
	  CONSTRAINT CATALOGO_LUGAR_FK FOREIGN KEY (idLugar)
      REFERENCES LUGAR (idLugar) 
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE TIPO_ITEM (
	idTipoItem INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  quantidadePermitida DECIMAL(3) NOT NULL,
    CONSTRAINT TIPO_ITEM_PK PRIMARY KEY (idTipoItem)
) ENGINE = InnoDB;

CREATE TABLE ITEM (
	idItem INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  preco DECIMAL(6,2) NOT NULL,
  idTipoItem INT NOT NULL,
  idCatalogo INT NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (idItem),
	  CONSTRAINT ITEM_TIPO_ITEM_FK FOREIGN KEY (idTipoItem)
      REFERENCES TIPO_ITEM (idTipoItem)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT ITEM_CATALOGO_FK FOREIGN KEY (idCatalogo)
      REFERENCES CATALOGO (idCatalogo)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE ITEM_PEDIDO (
	quantidade DECIMAL(10) NOT NULL,
  idItem INT NOT NULL,
  idPedido INT NOT NULL,
    CONSTRAINT ITEM_PEDIDO_ITEM_FK FOREIGN KEY (idItem)
      REFERENCES ITEM (idItem)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
	  CONSTRAINT ITEM_PEDIDO_PEDIDO_FK FOREIGN KEY (idPedido)
      REFERENCES PEDIDO (idPedido)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE = InnoDB;